### ISSUE TITLE
HU01_001_Validación de pre condiciones

### ISSUE THREAD

**Issue by vijhn** [jhon1125572/750092M-DesarrollodesoftwareII-Personalcollectionmovies#2]
# **Descripción**

Se debe responder a la siguientes preguntas antes de continuar con el desarrollo del modulo funcional.
## **Criterios de aceptación**

Se deben seguir los siguientes **criterios de aceptación** para poder cerrar la tarea.
- ¿El diseño actual de la base de datos permite el registro, modificación, obtención y eliminación de datos de un usuario?
- ¿Se generaron correctamente las interfaces de conexión con la base de datos como lo son los objetos de dominio y daos?

**Comment by ghost** [comment]
**¿Que se debería hacer?**
Se debe realizar un comentario en la tarea adjuntando la parte del diagrama que nos interesa y justificando por que se garantizan los criterios de aceptación.

**Comment by vijhn** [comment]
Bajo el esquema actual que posee la base de datos se puede garantizar el registro, modificación, obtención y eliminación de datos del usuario. El atributo erased corresponde a una cuenta de usuario eliminada, no se borraran datos de base de datos como tal. A futuro se pretende implementar la recuperación de cuentas de usuario. Adjunto las tablas que nos interesan para las operaciones indicadas.

**USERACCOUNT** 
(_**username**_, first_name, second_name, last_name, birth_date, gender, country, email, erased)

Respecto a la segunda parte, se han generado correctamente los objetos de dominio en la ruta /home/ubuntu/workspace/src/ws-personalcollectionmovies/model/domain

Se cierra la tarea.
