### ISSUE TITLE
Diseño de la base de datos [Diagrama ER]

### ISSUE THREAD

**Issue by vijhn** [jhon1125572/750092M-DesarrollodesoftwareII-Personalcollectionmovies#21]
# **Descripción**

Se debe realizar el diseño entidad relación que cumpla con las necesidades transaccionales de la aplicación para los requisitos definidos en la primera entrega.

**Comment by ghost** [comment]
Se adjunta documento de modelo de datos de la aplicación que contiene el Diagrama Entidad-Relación y documentación de las tablas. [Entrega IV [Modelo de Datos]](https://docs.google.com/document/d/1mm95T1em6-xtWsfjfk9tZHC0Wwn2WR3-zqG-ebzW21A/edit)

**Comment by ghost** [comment]
Se cierra la tarea.
