### ISSUE TITLE
HU06_001_Validación de pre condiciones.

### ISSUE THREAD

**Issue by ghost** [jhon1125572/750092M-DesarrollodesoftwareII-Personalcollectionmovies#24]
# **Descripción**

Se debe responder a la siguientes preguntas antes de continuar con el desarrollo del modulo funcional.
## **Criterios de aceptación**

Se deben seguir los siguientes **criterios de aceptación** para poder cerrar la tarea.
- ¿El diseño actual de la base de datos permite registrar, modificar y eliminar comentarios de un usuario para una película?
- ¿Se generaron correctamente las interfaces de conexión con la base de datos como lo son los objetos de dominio y daos?

**Comment by vijhn** [comment]
Las interfaces de conexión se realizaron correctamente junto a los daos de la base de datos.
