### ISSUE TITLE
HU01_002_001_Permitir registrar un usuario [register.html].

### ISSUE THREAD

**Issue by vijhn** [jhon1125572/750092M-DesarrollodesoftwareII-Personalcollectionmovies#30]

**Comment by ghost** [comment]
Hola @jhon1125572,

Se termino la creación del formulario y la interfaz de obtención de datos con golang. Se procede con la validación de datos usando beego/validate. 

Saludos.

**Comment by ghost** [comment]
Hola @jhon1125572, 
- Se termina el desarrollo de las vaidaciones usando JavaScript y beego/validate. 
- Se termina el proceso transaccional con la base de datos se debe crear una tarea de tipo mejora para controlar las sesiones de apertura de base de datos. 
- Se permite registrar un usuario y mostrar le mensaje respectivo en caso de que ocurra algún error.

Se da por terminada la tarea. Los cambios se han acomitado sobre la rama wspcm_v1.0.3.
