### ISSUE TITLE
HU14_Permitir acceso superusuario.

### ISSUE THREAD

**Issue by vijhn** [jhon1125572/750092M-DesarrollodesoftwareII-Personalcollectionmovies#56]
# **Descripción**

Se define la épica para la historia de usuario **HU-01** definida como:

> _Como administrador necesito acceso total a la aplicación, con la finalidad de poder administrar el sitio._
## **Criterios de aceptación**

Se deben seguir los siguientes **criterios de aceptación** para poder cerrar la tarea.
- ¿Se garantiza que el usuario de tipo administrador tenga acceso a todas las funcionalidades de la aplicación descritas en estas Historias de Usuario?
- ¿Se genera la auditoría de la operación realizada por el usuario?
- En caso de generarse un error en el código, ¿se generan los logs para su mantenimiento?
- En caso de que no se puede llevar a cabo el proceso, ¿se le informa al usuario la razón por la cual no pudo ser posible?

**Comment by ghost** [comment]
Se terminaron todas las sub tareas, se cierra la épica.
